OLED_ENABLE = yes
OLED_DRIVER = SSD1306      # Enables the use of OLED displays
ENCODER_ENABLE = no       # Enables the use of one or more encoders
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
MOUSEKEY_ENABLE = no
VIA_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes # Enables the ability to modify the mod tap term
BOOTMAGIC_ENABLE = yes
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes